# Generated by Django 4.2.2 on 2023-07-03 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='description',
            field=models.TextField(default='증말 맛있어요!'),
        ),
        migrations.AlterField(
            model_name='place',
            name='hates_num',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='place',
            name='image',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='likes_num',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
