# Generated by Django 4.2.3 on 2023-07-05 12:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('places', '0002_alter_place_description_alter_place_hates_num_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='hate_user',
            field=models.ManyToManyField(related_name='hate_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='place',
            name='like_user',
            field=models.ManyToManyField(related_name='like_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
