# Generated by Django 4.2.3 on 2023-07-06 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_alter_place_hate_user_alter_place_like_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='time',
        ),
    ]
