# Generated by Django 4.2.3 on 2023-07-07 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_remove_place_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='category',
            field=models.CharField(default='음식점', max_length=150),
        ),
    ]
