# Generated by Django 4.2.3 on 2023-07-07 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_alter_place_category'),
        ('places', '0008_alter_place_category_alter_place_link'),
    ]

    operations = [
    ]
