# Generated by Django 4.2.3 on 2023-07-08 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0009_merge_20230707_2150'),
        ('places', '0009_remove_place_hates_num_remove_place_likes_num'),
    ]

    operations = [
    ]
