# Generated by Django 4.2.3 on 2023-07-09 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0009_remove_place_hates_num_remove_place_likes_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='hates_num',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='place',
            name='likes_num',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
