# Generated by Django 4.2.3 on 2023-07-09 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0010_place_hates_num_place_likes_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='hates_num',
        ),
        migrations.RemoveField(
            model_name='place',
            name='likes_num',
        ),
    ]
