# Generated by Django 4.2.2 on 2023-07-03 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userId',
            field=models.CharField(default='quddyddlrk', max_length=30),
            preserve_default=False,
        ),
    ]
